# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwiftWorkspace' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSwiftWorkspace

    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'Kingfisher'
    pod 'SnapKit'
    pod 'Moya/RxSwift'
    pod 'SwiftyAttributes'
    pod 'HandyJSON'
    pod 'IQKeyboardManagerSwift'
    pod 'Toast-Swift'

end
