# Uncomment the next line to define a global platform for your project

platform :ios, '11.0'

target 'RxSwiftWorkspace' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSwiftWorkspace

    pod 'RxSwift'
    pod 'RxCocoa' 
    pod 'RxDataSources'
    pod 'NSObject+Rx'

    pod 'Moya/RxSwift'
    pod 'HandyJSON'

    pod 'Then'
    pod 'SnapKit'
    pod 'Kingfisher'
    pod 'Toast-Swift'
    pod 'SwiftyAttributes'
    pod 'TextFieldEffects'
    pod 'IQKeyboardManagerSwift'
    pod 'TangramKit'

    pod 'SSCustomTabbar'
    pod "ESTabBarController-swift"
    
    
    pod 'LookinServer', :configurations => ['Debug']

end
