# Uncomment the next line to define a global platform for your project

platform :ios, '11.0'

#install! 'cocoapods', :generate_multiple_pod_projects => true

target 'RxSwiftWorkspace' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSwiftWorkspace

  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
  pod 'NSObject+Rx'
  
  pod 'Moya/RxSwift'
  pod 'HandyJSON'

  pod 'Then'
  pod 'SnapKit'

  pod 'Toast-Swift'
  pod 'SwiftyAttributes'
  pod 'TextFieldEffects'
  pod 'IQKeyboardManagerSwift'


  pod 'SSCustomTabbar'
  pod "ESTabBarController-swift"
  pod 'AttributedString'

  pod 'SwiftLint'

  pod 'MJRefresh'

  pod 'LookinServer', :configurations => ['Debug']

end
